### PR TITLE
Throw a static instance in FillBuff

### PR DESCRIPTION
**Pull request by schorrm**
Very similar to PR #99. Removes a lot of performance overhead from building stack traces that will be discarded.

### CODE REVIEW

**Comment by MarcMazas** [comment]
Noted. We will see to integrate it when we have a test suite on which we have assessed the coverage.
Note that PRs must be signed to be mergeable.

**Comment by zbynek** [comment]
The same fix should be applied to JavaCharStream; also both JavaCharStream and SimpleCharStream are currently duplicated in the `gwt` folder, I'd suggest to apply the same fix there.

**Comment by schorrm** [comment]
@zbynek done, in #284

**Comment by schorrm** [comment]
closing in favor #284

**Pull request closed without merging**
