### PR TITLE
Spaghetti code fix ?

### PR DESCRIPTION
**Pull request by Risavk**
Simple change to create "non nesting" logic.
Existing solution created if (...) -> if (...) -> if (...) ->if (...) multiple nested construction. 
I stumbled on that when compiler raised error of too big level of if-nesting (JavaCC created nested logic higher than 256 if i remember correctly) ...

### CODE REVIEW

**Comment by new-javacc** [comment]
Do you have an example grammar that produces more than 256 levels? I'm a bit hesitant to touch the lookahead logic as it's pretty gnarly.

Also, I'm not sure if you are actively following the project, but we have a new branch 8.0.0 that *completely* decouples the code gen from the core. There we have full freedom to redo the whole thing in a much easier way. Please see if you want to contribute that effort and may be bring the generated code to the latest java standards.

**Comment by Risavk** [comment]
Nope. No "example" project. 
Working on mainframe cobol '85 grammar, and for now it is not shareable...
Maybe i'll extract fragment that created such a terrible LA... 
Thanks for hint about 8.0.0. Will check.

**Comment by Risavk** [comment]
Ha ! 
But i think that Cobol.jj, the one incorpporated in javacc grammars, works like that out of box. 
Of course after changing output language to c++.
Long time and few other parser generators and i forgot :D

**Comment by new-javacc** [comment]
Great! I will look into it.

**Comment by zosrothko** [comment]
@Risavk Could you backport your PR to the 8.0.0 branch? TIA

**Comment by raipc** [comment]
This change seems to have a defect. The function must not return false because there may be other conditions below. [JavaCC](https://github.com/JSQLParser/JSqlParser) tests are failing with new version
 Compare the following pseudocodes and truth tables

```java
if (a) {
    return true;
}
return b;
```

| a | b | res |
|---|--|----|
| F | F |  F |
| F | T | T |
| T | F | T |
| T | T | T  |

```java
if (!a) {
    return false;
}
return b;
```

| a | b | res |
|---|--|----|
| F | F |  F |
| F | T | F |
| T | F | F |
| T | T | T |

**Comment by zosrothko** [comment]
@Risavk plesae specify which version or branch you are testing?

**Comment by raipc** [comment]
@zosrothko I was testing on release 7.0.5

**Comment by raipc** [comment]
What do you think about following approach?

```java
label_b:
{
    if (!a) {
        break label_b;
    }
    if (b) {
        return true;
    }
}
return c;
```

**Comment by zosrothko** [comment]
@Risavk For all generation issues, please ask first @new-javacc . If there is a disagreement with Screeni, I could have a look, but he has the latest cut as owner of JavaCC

**Comment by new-javacc** [comment]
Oh no! :( I knew something didn't look right. We should really get 8.0.0 out so people will have the freedom to do codegen without affecting other users. @Risavk  can you revert the PR? Thanks!

**Pull request merged**
