### PR TITLE
Documentation of getNextToken

### PR DESCRIPTION
**Pull request by albert-github**
- place documentation at right place
- see to it that <EOF> is handled properly in the documentation

### CODE REVIEW

**Comment by zosrothko** [comment]
Can you backport your PR to the 8.0.0 branch. Thx

**Comment by albert-github** [comment]
Is the backport still necessary?

**Comment by mbrigl** [comment]
All language specific code is in the sub-module  [javacc/codegenerator](https://github.com/javacc/codegenerator)

**Comment by albert-github** [comment]
I've just pushed a proposed patch for version 8.0.0: https://github.com/javacc/codegenerator/pull/64

**Pull request merged**
