### PR TITLE
Java codegen implementation

### PR DESCRIPTION
**Pull request by mbrigl**
requires breaking changes in the .jjt file. It is not anymore possible to parse from .jjt
 the package, import, extends, implements for java

### CODE REVIEW

**Comment by zosrothko** [comment]
Can you push also this PR against the branch csharp_codegen? Thx

**Comment by mbrigl** [comment]
sure? the branch _csharp_codegen_ uses still the previous structure

**Comment by new-javacc** [comment]
I don't really see a need for it. I think we should close all the other branches and just move everything to 8.0.0 branch.On Sep 24, 2018 11:19 AM, Markus Brigl <notifications@github.com> wrote:sure? the branch csharp_codegen uses still the previous structure

**Comment by zosrothko** [comment]
@new-javacc  I asked @mbrigl  to push also his PR to the csharp_codegen branch because I did not if you were in sync or not with the move to the 8.0.0 branch as you did not answer or react to this proposal on the Slack #general channel. If everybody is on the 8.0.0 branch, then the csharp_codegen can be deleted.

**Pull request merged**
