### PR TITLE
Add const as modifier in formal parameter

### PR DESCRIPTION
**Pull request by zosrothko**
Hi

this PR makes JavaCC accepting such C++ syntax:

```
void Foo(const Token* const t) : 
{  }
{
}
```

### CODE REVIEW

**Comment by new-javacc** [comment]
I'm reluctant to do this. You can always do a t   use a typedef in C++ for this. If you noticed, my goal is to keep the JavaCC syntax free of language-specific stuff as much as possible.

**Comment by new-javacc** [comment]
To be sure, I want to remove the entire java grammar from the JavaCC parser. If there is a lot of interest we can extend the language (code generator) plugin to provide functions to validate the various language specific parts of JavaCC input grammars like return type, parameters, exceptions, semantic look ahead and action blocks. What we have right now is just java stuff and adding const to that is not clean. It just looks like a hack.

If you really want to fix it, fix the JavaCC grammar to also skip parsing parameters entirely (and just grab the tokens) like we do for actions in C++. And please no more CPP specific options either. Thanks!

**Comment by new-javacc** [comment]
Just to be sure - please keep all your C++ specific changes in 7.x branch. I'm doing major changes in main so these will get lost eventually. Like I said JavaCC 8.0 will be very different and much trimmed down/streamlined. So please do not merge anything to master. Thanks!

**Comment by zosrothko** [comment]
" please keep all your C++ specific changes in 7.x branch". I am keeping all my C++ changes in the 7.1.0 branch and a specific branch that will never be published. The "const" change seems to me a general change that matches the overall C++ stuff in JavaCC.

**Comment by new-javacc** [comment]
see my comment above. I' going to remove *all* language specific tokens so no point in fixing this as it will be removed.

**Comment by new-javacc** [comment]
Also note that you can bring back your 7.1 branch as a code generator after my refactoring. So please b patient :)

**Pull request closed without merging**
