### PR TITLE
Codegenerator implementation for C++

### PR DESCRIPTION
**Pull request by mbrigl**
One-to-one migration from the CppOutput to the C++ CodeGenerator. The CppOutput mechanism is still available for crosschecks.
The next step is to remove all CPP parts from the core. Should we do the same for Java?

### CODE REVIEW

**Comment by mbrigl** [comment]
JavaCC is still based on Java 5. Is there a reason for that? Would it be a problem to migrate JavaCC to at least Java 8? Before I continue to develop the C++ CodeGenerator, I would like to clean up the code, e.g. Remove static access to variables (LexGen) wherever possible.

**Comment by kaikalur** [comment]
To be even more clear - the code generator just receives the TokenizerData and ParserData objects and after that it's all upto the code generator. So for now, I suggest leaving the core javacc alone and doing all cool stuff in the new code generators so we maintain the stability. Once this stuff stabilizes, we can work on Core. Also note that we are making breaking changes so the new code does not have to have any resemblance to the old one.

**Comment by mbrigl** [comment]
> So for now, I suggest leaving the core javacc alone and doing all cool stuff in the new code generators so we maintain the stability. Once this stuff stabilizes, we can work on Core. Also note that we are making breaking changes so the new code does not have to have any resemblance to the old one.

Ok, that makes sense for me. Nevertheless, it would be helpful to do some **not breaking** cleaning in the core (especially before a major change like this): 

- Migrate to an newer Java version and consistent use of _generics_ (you are an insider, I'm new to the source code & it's easier to understand with typed collections and maps)
- The maven works only if ant is called before to generate the source. I would fix it, and replace ant. With your new approach I would suggest a maven project with sub-modules (for each CodeGenerator a proper module)
- There is some useless code (e.g. ASTLHS is not used anymore, others can be remove because not different from generated source...).

I like to help, but I want to make sure that my work is not meaningless. E.g my little, but important, bugfix #51 is still not merged.

**Comment by kaikalur** [comment]
I'm ok with everything except getting rid of ant :) I'm old school. I still like to type ant get it built. Please go ahead and make the other changes but keep in mind that in javacc we do not use any third party libraries (at least in the core) so as long as you stick to that, it should be ok.

I will ask Kesav to give you write/merge permissions to the repo so you can merge it yourself.

And thank you very much for all the contrib!

**Comment by mbrigl** [comment]
> SO IIUC, you are simply refactoring the existing code generator, right? So can we also completely delete at least legacy C++ code - so let's get rid of all isLanguageCpp blocks in the javacc core. WDYT?

Wait still a few weeks. I'm new to the framework. I did some tests and they all went fine, but I want to do more test before removing the current c ++ generator.

Currently I cloned/migrated most of the C++ code to the CodeGenerator. Especially the TokenManagerCodeGenerator is only a first version and should be realized differently.

In the core of JavaCC I extracted the JavaCode from the LexGen in a proper LexGenJava. And in the main I removed the invocation of the CodeGenerator from the condition _isJavaOutput_. Maybe you have a look at the commit [Split JavaOutput from CodeGenerators & Lexers](https://github.com/mbrigl/javacc/commit/b9489fa1c19640cbd6e13d574c2e8a863a932ceb)

**Comment by mbrigl** [comment]
>  but keep in mind that in javacc we do not use any third party libraries 

That's why I like JavaCC

> I still like to type ant get it built.

With maven you would get the same, but it's okay

> I will ask Kesav to give you write/merge permissions

Thanks, but the first contributions, I prefer that you guys check them.

**Comment by kaikalur** [comment]
OK. For C++, I have one test under examples/JavaGrammars/cpp. There is a makefile everything so it should just work. It tests both char and wchar_t versions. That should test most of the grammar features.

**Comment by new-javacc** [comment]
Hi Markus,

I just merged your pull request into the csharp_codegen branch.

Regards,
Kesav

**Pull request merged**
